### PR TITLE
FT: #8 add sandwich estimator and test

### LINKED ISSUE #8: FT: Write a sandwich estimator function + Vignette on `lm` object
- [x] Update version number for our package using `usethis::use_version()`. Then update `NEWS.md` with appropriate feature release information
- [x] Ensure that we have `BibTeX` citations correct in our `roxygen2` comments for our functions
- [x] Add in unit test where naive `solve` based variance estimator is unstable by construction. See such an [example for a linear model here](https://genomicsclass.github.io/book/pages/qr_and_regression.html?fbclid=IwAR13XgfiJ3X5sNSsHtiaaVn8nW3l5Hm30WGARA3a37YcDeDBMqe7eLZ4u6M). We should show that our unit test shows that `qr` and `sandwich::sandwich` estimator are equal to each other, but naive `solve` based estimator is not equal to 7 dec. pl.
- [x] Write a benchmark using the `bench` package to the `sandwich::sandwich` estimator. See [here for an example](https://github.com/tidyverse/dplyr/blob/master/bench/bench-distinct.R), we would need to create a `bench` dir and add a dependency on the `bench` package.
- [x] Write the unit test to show the numerical instability of the naive variance sandwich estimator implementation using `solve`. We should show that we do **not** match to 7 dec. pl. when we match to the other `sandwich` estimator. This naive estimator can be included in our `test-ols-var.R` file and not in our `maar` package
- [x] Write a unit test to check our sandwich estimator using the manual `solve` based approach. The `solve` based approach should be less computationally efficient.
- [x] Write a unit test to check our sandwich estimator using Arun's regression approach
- [x] Update our sandwich estimator using `Matrix` package and the [QR decomposition](https://genomicsclass.github.io/book/pages/qr_and_regression.html?fbclid=IwAR13XgfiJ3X5sNSsHtiaaVn8nW3l5Hm30WGARA3a37YcDeDBMqe7eLZ4u6M)
- [x] Set a seed for the unit tests
- [x] Write a unit test to check our sandwich estimator against the `sandwich::sandwich` estimator
- [x] Create a file called `ols-var.R` and an associated `test-ols-var.R` function
- [x] Implement a function to calculate the sandwich estimator of the variance
- [x] Add correct citations for [Models As Approximations](https://projecteuclid.org/euclid.ss/1578474013#toc) papers in `README.Rmd`
- [x] Add a [citation for the package](https://github.com/r-lib/usethis/issues/100#issuecomment-442582347)

### PR DESCRIPTION
**Pull request by ricfog**
This is for #8 

- [x] Update version number for our package using `usethis::use_version()`. Then update `NEWS.md` with appropriate feature release information
- [x] Ensure that we have `BibTeX` citations correct in our `roxygen2` comments for our functions
- [x] Add in unit test where naive `solve` based variance estimator is unstable by construction. See such an [example for a linear model here](https://genomicsclass.github.io/book/pages/qr_and_regression.html?fbclid=IwAR13XgfiJ3X5sNSsHtiaaVn8nW3l5Hm30WGARA3a37YcDeDBMqe7eLZ4u6M). We should show that our unit test shows that `qr` and `sandwich::sandwich` estimator are equal to each other, but naive `solve` based estimator is not equal to 7 dec. pl.
- [x] Write a benchmark using the `bench` package to the `sandwich::sandwich` estimator. See [here for an example](https://github.com/tidyverse/dplyr/blob/master/bench/bench-distinct.R), we would need to create a `bench` dir and add a dependency on the `bench` package.
- [x] Write the unit test to show the numerical instability of the naive variance sandwich estimator implementation using `solve`. We should show that we do **not** match to 7 dec. pl. when we match to the other `sandwich` estimator. This naive estimator can be included in our `test-ols-var.R` file and not in our `maar` package
- [x] Write a unit test to check our sandwich estimator using the manual `solve` based approach. The `solve` based approach should be less computationally efficient.
- [x] Write a unit test to check our sandwich estimator using Arun's regression approach
- [x] Update our sandwich estimator using `Matrix` package and the [QR decomposition](https://genomicsclass.github.io/book/pages/qr_and_regression.html?fbclid=IwAR13XgfiJ3X5sNSsHtiaaVn8nW3l5Hm30WGARA3a37YcDeDBMqe7eLZ4u6M)
- [x] Set a seed for the unit tests
- [x] Write a unit test to check our sandwich estimator against the `sandwich::sandwich` estimator
- [x] Create a file called `ols-var.R` and an associated `test-ols-var.R` function
- [x] Implement a function to calculate the sandwich estimator of the variance
- [x] Add correct citations for [Models As Approximations](https://projecteuclid.org/euclid.ss/1578474013#toc) papers in `README.Rmd`
- [x] Add a [citation for the package](https://github.com/r-lib/usethis/issues/100#issuecomment-442582347)

### CODE REVIEW

**Comment by shamindras** [comment]
@ricfog - here are the steps to include your new modifications to the sandwich estimator (this is a fairly generic workflow for you to use for an existing PR, and branch that you have linked to the PR locally):

1. **terminal:** `cd` to your local `maar` repo
2. **terminal:** `git checkout iss-08-sandwich-vignette` to ensure you are in the correct branch. You should also type `git branch` to verify this
3. **terminal:** `git pull` to ensure you have pulled down the latest changes since your last commit
4. **terminal:** `open -a /Applications/RStudio.app maar.Rproj` which should open up a separate `maar` RStudio project
5. **RStudio:** open the `R/maa-ols.R` and modify the function
6. **RStudio:** Ensure that you add in explicit references to outside packages e.g. `Matrix`. So I believe your code will look like this:
	``` R
	comp_sandwich_var <- function(lm_object) {
	  qR <- base::qr.R(lm_object$qr)
	  J_inv <- base::chol2inv(qR)
	  X <- base::qr.X(lm_object$qr)
	  V <- t(X) %*% Matrix::Diagonal(x = lm_object$residuals^2) %*% X
	  base::return(unname(J_inv %*% V %*% J_inv))
	}
	```
7. **RStudio:** Add the `Matrix` package as a dependency for `maar` i.e. `usethis::use_package("Matrix")`
8. **RStudio:** Click inside the function, and in RStudio select `Code > Insert Roxygen2 Skeleton`. It should update the existing `roxygen2` comment with the `lm_object` parameter. You should manually remove the old, unused parameters `roxygen2` comments
8. I think it would be good to set a seed in our test file i.e. open the `tests/testthat/test-maa-ols.R` file and add a `base::set.seed(seed = )` with any value of your choice
9. **RStudio:** In the console run the line: `devtools::document();devtools::load_all();devtools::test()`. Check that everything passes. Hopefully the tests should be much faster now 👍 
10. **terminal:** Go to the top level `maar` directory i.e. you should be inside the `maar` repo again, but at the top level directory. Now run `make build_pkgdown`. Check that there are no errors.
11. **terminal:** Run `git status` and check that only the files you intended are updated, `pkgdown` will update other files as well
12. **terminal:** Run `git add --all` and then `git status` to check their status has changed correctly
13. **terminal:** Then commit e.g. `git commit -m "FT: #8 speed up sandwich estimator using QR decomposition and Matrix package`
14. **terminal:** Run `git pull` just to ensure that there are no further changes in the repo. If there are you may just have to accept and commit them i.e. `git` will open up the editor with the message and you may have to accept them and close the editor. If there are conflicts 😬 then you may have to fix them, and save and commit. Ask for help if this happens
15. **terminal:** Finally run `git push` and then go to this [PR](https://github.com/shamindras/maar/pull/10) and check that your commit appears.
16. Take a minute to celebrate your win ✌️ , but then focus, there are many more commits to go

File: tests/testthat/test-ols-var.R [hunk 1]
```diff
@@ -1,12 +1,25 @@
+set.seed(1)
 test_that("lm and sandwhich variance - 4 dec.pl.", {
```
Comment (shamindras) [inline tests/testthat/test-ols-var.R]: @ricfog - I think we can change this to `7 dec. pl.`

File: tests/testthat/test-ols-var.R [hunk 2]
```diff
@@ -1,12 +1,25 @@
...
+  n <- 1e5
+  X <- stats::rnorm(n, 0, 1)
+  y <- 2 + X * 1 + stats::rnorm(n, 0, 10)
+  lm_fit <- stats::lm(y ~ X)
+  sandwich_qr_var <- comp_sandwich_qr_var(lm_fit)
   expect_equal(
-    round(broom::tidy(lm_fit)$std.error, 3),
-    round(sqrt(diag(sandwich_var)), 3)
+    round(broom::tidy(lm_fit)$std.error, 4),
+    round(sqrt(diag(sandwich_qr_var)), 4)
```
Comment (shamindras) [inline tests/testthat/test-ols-var.R]: We can change the rounding to 7 dec. pl. Our test is more robust now since our function is numerically better

File: tests/testthat/test-ols-var.R [hunk 3]
```diff
@@ -1,12 +1,25 @@
...
+test_that("sandwich variance from our estimator and estimator from Sandwich pkg - 4 dec.pl.", {
+  n <- 1e5
+  X <- stats::rnorm(n, 0, 1)
+  y <- 2 + X * 1 + stats::rnorm(n, 0, 10)
+  lm_fit <- stats::lm(y ~ X)
+  sandwich_sandpkg_var <- sandwich::sandwich(lm_fit)
+  sandwich_qr_var <- comp_sandwich_qr_var(lm_fit)
+  expect_equal(
+    c(round(sandwich_sandpkg_var, 4)),
+    c(round(sandwich_qr_var, 4))
```
Comment (shamindras) [inline tests/testthat/test-ols-var.R]: Please change from 4 dec. pl. to 7 dec. pl

File: tests/testthat/test-ols-var.R [hunk 4]
```diff
@@ -1,12 +1,25 @@
...
+  sandwich_qr_var <- comp_sandwich_qr_var(lm_fit)
   expect_equal(
-    round(broom::tidy(lm_fit)$std.error, 3),
-    round(sqrt(diag(sandwich_var)), 3)
+    round(broom::tidy(lm_fit)$std.error, 4),
+    round(sqrt(diag(sandwich_qr_var)), 4)
   )
 })
 
+test_that("sandwich variance from our estimator and estimator from Sandwich pkg - 4 dec.pl.", {
```
Comment (shamindras) [inline tests/testthat/test-ols-var.R]: We can again change from 4 dec. pl. to 7 dec. pl.

**Review by shamindras — CHANGES_REQUESTED** [review]
@ricfog - great work!

Very minor changes below. I would also recommend running `styler` on the code and test files before pushing the code. Just treat this as a fun way to practice an implementation of PR review changes.

Also one high level question, you currently generate the same data for both tests:

``` R
n <- 1e5
X <- stats::rnorm(n, 0, 1)
y <- 2 + X * 1 + stats::rnorm(n, 0, 10)
lm_fit <- stats::lm(y ~ X)
```

So perhaps you can just generate this data once at the top of the file
outside the `test_that` functions and then just call the common `lm_fit`
object into both tests perhaps e.g. we could just have:

``` R
set.seed(1246426)

n <- 1e5
X <- stats::rnorm(n, 0, 1)
y <- 2 + X * 1 + stats::rnorm(n, 0, 10)
lm_fit <- stats::lm(y ~ X)
NUM_DEC_PL <- 7

test_that("lm and sandwhich variance", {
  sandwich_qr_var <- comp_sandwich_qr_var(lm_fit)
  expect_equal(
    round(broom::tidy(lm_fit)$std.error, NUM_DEC_PL),
    round(sqrt(diag(sandwich_qr_var)), NUM_DEC_PL)
  )
})

test_that("sandwich variance from our estimator and estimator from Sandwich pkg", {  
  sandwich_sandpkg_var <- sandwich::sandwich(lm_fit)
  sandwich_qr_var <- comp_sandwich_qr_var(lm_fit)
  expect_equal(
    c(round(sandwich_sandpkg_var, NUM_DEC_PL)),
    c(round(sandwich_qr_var, NUM_DEC_PL))
  )
})
```

What do you think?

File: tests/testthat/test-ols-var.R [hunk 5]
```diff
@@ -0,0 +1,25 @@
+set.seed(1)
```
Comment (shamindras) [inline tests/testthat/test-ols-var.R]: I would recommend changing the seed from something other than `1` to say `1246426` for example

File: tests/testthat/test-ols-var.R (hunk 4 above)
Comment (ricfog) [reply tests/testthat/test-ols-var.R]: It seems that our estimator matches the variance estimated by the sandwich package up to the 7th decimal place, but the one by lm only up to the 4th decimal place.

**Review by shamindras — APPROVED** [review]

**Comment by shamindras** [comment]
@ricfog - we should now have `BibTeX` references in our function documentation. So when you run `help(comp_sandwich_qr_var)` it should look like this:

viewRd_maar_02
